services:
  - type: web
    name: vibe-prospecting
    runtime: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && NODE_ENV=production node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_M4xh1WrGNXDb@ep-snowy-pond-am5utxv4.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: DIRECT_DATABASE_URL
        value: postgresql://neondb_owner:npg_M4xh1WrGNXDb@ep-snowy-pond-am5utxv4.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://vibe-prospecting.onrender.com
